controller_list:
  - name: fake_all_joints_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
initial:  # Define initial robot poses.
  - group: all_joints
    pose: home